- name: Ensure Docker APT key is present
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Ensure Docker APT Repo is present
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: true

- name: Install docker and its dependecies
  apt: 
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present
    update_cache: yes
    notify:
      - docker status
  become: true

- name: Enable docker
  shell: systemctl enable docker
  become: true
